#!/bin/bash

file="$1"
oldver="$2"
version="$3"

sempl > "$file.new" <<-EOF
Version $version

Changelog:

* {!tail -n+5 "$file"}

See the README for a complete description of all packs: https://github.com/DMBuce/bucepack/tree/$version#buces-packs
EOF

mv "$file.new" "$file"

