#!/bin/bash

file="$1"
oldver="$2"
version="$3"

if [[ $version != "$(<cache/latest.txt)"* ]]; then
	version="$(<cache/latest.txt)-1"
fi

sempl > "$file.new" <<-EOF
Version $version

Changelog:

* {!tail -n+5 "$file"}

See the README for a complete description of all packs: https://github.com/DMBuce/bucepack/tree/$version#buces-packs

Note that Hardcore Lichdom hasn't been updated and only works on Minecraft 1.16.
EOF

mv "$file.new" "$file"

